# Generated by Django 2.0.3 on 2018-04-03 18:01

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='El formato del número no es válido.', regex='^\\+?1?\\d{9,15}$')])),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('rfc', models.CharField(max_length=100, null=True)),
                ('razon_social', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True, validators=[django.core.validators.EmailValidator(code=1, message='Correo inválido', whitelist=None)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
