# Generated by Django 2.0.2 on 2018-04-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='unidad',
        ),
        migrations.AddField(
            model_name='materialinventario',
            name='cantidad_salida',
            field=models.IntegerField(blank=True, null='True'),
        ),
        migrations.AddField(
            model_name='materialinventario',
            name='unidad_entrada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='materiales.Unidad'),
            preserve_default=False,
        ),
    ]
