# Generated by Django 2.0.2 on 2018-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='estatus',
            field=models.IntegerField(default=1),
        ),
    ]
