# Generated by Django 2.0.2 on 2018-02-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
