# Generated by Django 2.0.2 on 2018-02-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0002_auto_20180227_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
