# Generated by Django 2.0.4 on 2018-04-03 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ordenes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus_Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplicador', models.IntegerField(validators=[ordenes.models.validate_no_multiplicadores_menores_a_0])),
                ('estatus', models.CharField(choices=[('0', 'Cancelada'), ('1', 'Por Trabajar'), ('2', 'Listo')], default='1', max_length=1)),
                ('fecha_fin', models.DateField(blank=True, null=True, validators=[ordenes.models.validate_fecha_mayor_fecha_actual])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.Receta')),
            ],
        ),
    ]
