# Generated by Django 2.0.2 on 2018-03-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='relacionrecetamaterial',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='relacionrecetamaterial',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
