# Generated by Django 2.0.2 on 2018-02-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='material',
            field=models.ManyToManyField(to='materiales.Material'),
        ),
    ]
